#include "Settings.h"
VOID Setting::ReadRendererSettings() {
	if (miscs::get().exists((miscs::get().GetProgramPath() + "\\Config.ini").c_str()))
	{
		char* ConfigPath = new char[MAX_PATH];
		strcpy(ConfigPath, (miscs::get().GetProgramPath() + "\\Config.ini").c_str());
		Draw::get().SleepTime = miscs::get().ReadIni_float(ConfigPath, "性能设置", "绘制性能(0-5 0为最高性能)");
	}
}
VOID Setting::ReadColorSettings() {
	if (miscs::get().exists((miscs::get().GetProgramPath() + "\\Config.ini").c_str())) 
	{
		char* ConfigPath = new char[MAX_PATH];
		strcpy(ConfigPath, (miscs::get().GetProgramPath() + "\\Config.ini").c_str());
		this->ColorPlayer.x = miscs::get().ReadIni_float(ConfigPath, "玩家", "文本颜色值R") / 255.f;
		this->ColorPlayer.y = miscs::get().ReadIni_float(ConfigPath, "玩家", "文本颜色值G") / 255.f;
		this->ColorPlayer.z = miscs::get().ReadIni_float(ConfigPath, "玩家", "文本颜色值B") / 255.f;
		this->ColorBox.x = miscs::get().ReadIni_float(ConfigPath, "玩家", "方框颜色值R") / 255.f;
		this->ColorBox.y = miscs::get().ReadIni_float(ConfigPath, "玩家", "方框颜色值G") / 255.f;
		this->ColorBox.z = miscs::get().ReadIni_float(ConfigPath, "玩家", "方框颜色值B") / 255.f;
		this->ColorRay.x = miscs::get().ReadIni_float(ConfigPath, "射线", "颜色值R") / 255.f;
		this->ColorRay.y = miscs::get().ReadIni_float(ConfigPath, "射线", "颜色值G") / 255.f;
		this->ColorRay.z = miscs::get().ReadIni_float(ConfigPath, "射线", "颜色值B") / 255.f;
		this->ColorCorpse.x = miscs::get().ReadIni_float(ConfigPath, "尸体", "颜色值R") / 255.f;
		this->ColorCorpse.y = miscs::get().ReadIni_float(ConfigPath, "尸体", "颜色值G") / 255.f;
		this->ColorCorpse.z = miscs::get().ReadIni_float(ConfigPath, "尸体", "颜色值B") / 255.f;
		this->ColorNPC.x = miscs::get().ReadIni_float(ConfigPath, "NPC", "颜色值R") / 255.f;
		this->ColorNPC.y = miscs::get().ReadIni_float(ConfigPath, "NPC", "颜色值G") / 255.f;
		this->ColorNPC.z = miscs::get().ReadIni_float(ConfigPath, "NPC", "颜色值B") / 255.f;
		this->ColorOffline.x = miscs::get().ReadIni_float(ConfigPath, "离线玩家", "颜色值R") / 255.f;
		this->ColorOffline.y = miscs::get().ReadIni_float(ConfigPath, "离线玩家", "颜色值G") / 255.f;
		this->ColorOffline.z = miscs::get().ReadIni_float(ConfigPath, "离线玩家", "颜色值B") / 255.f;
		this->ColorStone.x = miscs::get().ReadIni_float(ConfigPath, "石头矿石", "颜色值R") / 255.f;
		this->ColorStone.y = miscs::get().ReadIni_float(ConfigPath, "石头矿石", "颜色值G") / 255.f;
		this->ColorStone.z = miscs::get().ReadIni_float(ConfigPath, "石头矿石", "颜色值B") / 255.f;
		this->ColorSulfur.x = miscs::get().ReadIni_float(ConfigPath, "硫磺矿石", "颜色值R") / 255.f;
		this->ColorSulfur.y = miscs::get().ReadIni_float(ConfigPath, "硫磺矿石", "颜色值G") / 255.f;
		this->ColorSulfur.z = miscs::get().ReadIni_float(ConfigPath, "硫磺矿石", "颜色值B") / 255.f;
		this->ColorMetal.x = miscs::get().ReadIni_float(ConfigPath, "金属矿石", "颜色值R") / 255.f;
		this->ColorMetal.y = miscs::get().ReadIni_float(ConfigPath, "金属矿石", "颜色值G") / 255.f;
		this->ColorMetal.z = miscs::get().ReadIni_float(ConfigPath, "金属矿石", "颜色值B") / 255.f;
		this->ColorHemp.x = miscs::get().ReadIni_float(ConfigPath, "大麻", "颜色值R") / 255.f;
		this->ColorHemp.y = miscs::get().ReadIni_float(ConfigPath, "大麻", "颜色值G") / 255.f;
		this->ColorHemp.z = miscs::get().ReadIni_float(ConfigPath, "大麻", "颜色值B") / 255.f;
		this->ColorMushroom.x = miscs::get().ReadIni_float(ConfigPath, "蘑菇", "颜色值R") / 255.f;
		this->ColorMushroom.y = miscs::get().ReadIni_float(ConfigPath, "蘑菇", "颜色值G") / 255.f;
		this->ColorMushroom.z = miscs::get().ReadIni_float(ConfigPath, "蘑菇", "颜色值B") / 255.f;
		this->ColorFoodBox.x = miscs::get().ReadIni_float(ConfigPath, "食品盒", "颜色值R") / 255.f;
		this->ColorFoodBox.y = miscs::get().ReadIni_float(ConfigPath, "食品盒", "颜色值G") / 255.f;
		this->ColorFoodBox.z = miscs::get().ReadIni_float(ConfigPath, "食品盒", "颜色值B") / 255.f;
		this->ColorPumpkin.x = miscs::get().ReadIni_float(ConfigPath, "南瓜", "颜色值R") / 255.f;
		this->ColorPumpkin.y = miscs::get().ReadIni_float(ConfigPath, "南瓜", "颜色值G") / 255.f;
		this->ColorPumpkin.z = miscs::get().ReadIni_float(ConfigPath, "南瓜", "颜色值B") / 255.f;
		this->ColorCorn.x = miscs::get().ReadIni_float(ConfigPath, "玉米", "颜色值R") / 255.f;
		this->ColorCorn.y = miscs::get().ReadIni_float(ConfigPath, "玉米", "颜色值G") / 255.f;
		this->ColorCorn.z = miscs::get().ReadIni_float(ConfigPath, "玉米", "颜色值B") / 255.f;
		this->Colorpotato.x = miscs::get().ReadIni_float(ConfigPath, "土豆", "颜色值R") / 255.f;
		this->Colorpotato.y = miscs::get().ReadIni_float(ConfigPath, "土豆", "颜色值G") / 255.f;
		this->Colorpotato.z = miscs::get().ReadIni_float(ConfigPath, "土豆", "颜色值B") / 255.f;
		this->ColorAnimal.x = miscs::get().ReadIni_float(ConfigPath, "动物", "颜色值R") / 255.f;
		this->ColorAnimal.y = miscs::get().ReadIni_float(ConfigPath, "动物", "颜色值G") / 255.f;
		this->ColorAnimal.z = miscs::get().ReadIni_float(ConfigPath, "动物", "颜色值B") / 255.f;
		this->ColorTank.x = miscs::get().ReadIni_float(ConfigPath, "武装坦克", "颜色值R") / 255.f;
		this->ColorTank.y = miscs::get().ReadIni_float(ConfigPath, "武装坦克", "颜色值G") / 255.f;
		this->ColorTank.z = miscs::get().ReadIni_float(ConfigPath, "武装坦克", "颜色值B") / 255.f;
		this->ColorArmedHelicopter.x = miscs::get().ReadIni_float(ConfigPath, "武装直升机", "颜色值R") / 255.f;
		this->ColorArmedHelicopter.y = miscs::get().ReadIni_float(ConfigPath, "武装直升机", "颜色值G") / 255.f;
		this->ColorArmedHelicopter.z = miscs::get().ReadIni_float(ConfigPath, "武装直升机", "颜色值B") / 255.f;
		this->ColorTurret.x = miscs::get().ReadIni_float(ConfigPath, "自动炮塔", "颜色值R") / 255.f;
		this->ColorTurret.y = miscs::get().ReadIni_float(ConfigPath, "自动炮塔", "颜色值G") / 255.f;
		this->ColorTurret.z = miscs::get().ReadIni_float(ConfigPath, "自动炮塔", "颜色值B") / 255.f;
		this->ColorTrap.x = miscs::get().ReadIni_float(ConfigPath, "散弹枪陷阱", "颜色值R") / 255.f;
		this->ColorTrap.y = miscs::get().ReadIni_float(ConfigPath, "散弹枪陷阱", "颜色值G") / 255.f;
		this->ColorTrap.z = miscs::get().ReadIni_float(ConfigPath, "散弹枪陷阱", "颜色值B") / 255.f;
		this->ColorAntiaircraftGun.x = miscs::get().ReadIni_float(ConfigPath, "防空炮塔", "颜色值R") / 255.f;
		this->ColorAntiaircraftGun.y = miscs::get().ReadIni_float(ConfigPath, "防空炮塔", "颜色值G") / 255.f;
		this->ColorAntiaircraftGun.z = miscs::get().ReadIni_float(ConfigPath, "防空炮塔", "颜色值B") / 255.f;
		this->ColorSupplyBox.x = miscs::get().ReadIni_float(ConfigPath, "补给箱", "颜色值R") / 255.f;
		this->ColorSupplyBox.y = miscs::get().ReadIni_float(ConfigPath, "补给箱", "颜色值G") / 255.f;
		this->ColorSupplyBox.z = miscs::get().ReadIni_float(ConfigPath, "补给箱", "颜色值B") / 255.f;
		this->ColorToolBox.x = miscs::get().ReadIni_float(ConfigPath, "工具箱", "颜色值R") / 255.f;
		this->ColorToolBox.y = miscs::get().ReadIni_float(ConfigPath, "工具箱", "颜色值G") / 255.f;
		this->ColorToolBox.z = miscs::get().ReadIni_float(ConfigPath, "工具箱", "颜色值B") / 255.f;
		this->ColorMilitaryBox.x = miscs::get().ReadIni_float(ConfigPath, "军工箱", "颜色值R") / 255.f;
		this->ColorMilitaryBox.y = miscs::get().ReadIni_float(ConfigPath, "军工箱", "颜色值G") / 255.f;
		this->ColorMilitaryBox.z = miscs::get().ReadIni_float(ConfigPath, "军工箱", "颜色值B") / 255.f;
		this->ColorSuperbox.x = miscs::get().ReadIni_float(ConfigPath, "超级军工箱", "颜色值R") / 255.f;
		this->ColorSuperbox.y = miscs::get().ReadIni_float(ConfigPath, "超级军工箱", "颜色值G") / 255.f;
		this->ColorSuperbox.z = miscs::get().ReadIni_float(ConfigPath, "超级军工箱", "颜色值B") / 255.f;
		this->ColorTerritoryBox.x = miscs::get().ReadIni_float(ConfigPath, "领地柜", "颜色值R") / 255.f;
		this->ColorTerritoryBox.y = miscs::get().ReadIni_float(ConfigPath, "领地柜", "颜色值G") / 255.f;
		this->ColorTerritoryBox.z = miscs::get().ReadIni_float(ConfigPath, "领地柜", "颜色值B") / 255.f;
	}
}
VOID setting() {
	char* ConfigPath = new char[MAX_PATH];
	strcpy(ConfigPath, (miscs::get().GetProgramPath() + "\\Config.ini").c_str());
	miscs::get().WriteIni_int(ConfigPath, "性能设置", "绘制性能(0-5 0为最高性能)", Draw::get().SleepTime);
	miscs::get().WriteIni_int(ConfigPath, "玩家文本", "颜色值R", Setting::get().ColorPlayer.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玩家文本", "颜色值G", Setting::get().ColorPlayer.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玩家文本", "颜色值B", Setting::get().ColorPlayer.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玩家方框", "颜色值R", Setting::get().ColorBox.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玩家方框", "颜色值G", Setting::get().ColorBox.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玩家方框", "颜色值B", Setting::get().ColorBox.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "射线", "颜色值R", Setting::get().ColorRay.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "射线", "颜色值G", Setting::get().ColorRay.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "射线", "颜色值B", Setting::get().ColorRay.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "尸体", "颜色值R", Setting::get().ColorCorpse.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "尸体", "颜色值G", Setting::get().ColorCorpse.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "尸体", "颜色值B", Setting::get().ColorCorpse.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "NPC", "颜色值R", Setting::get().ColorNPC.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "NPC", "颜色值G", Setting::get().ColorNPC.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "NPC", "颜色值B", Setting::get().ColorNPC.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "离线玩家", "颜色值R", Setting::get().ColorOffline.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "离线玩家", "颜色值G", Setting::get().ColorOffline.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "离线玩家", "颜色值B", Setting::get().ColorOffline.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "石头矿石", "颜色值R", Setting::get().ColorStone.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "石头矿石", "颜色值G", Setting::get().ColorStone.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "石头矿石", "颜色值B", Setting::get().ColorStone.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "硫磺矿石", "颜色值R", Setting::get().ColorSulfur.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "硫磺矿石", "颜色值G", Setting::get().ColorSulfur.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "硫磺矿石", "颜色值B", Setting::get().ColorSulfur.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "金属矿石", "颜色值R", Setting::get().ColorMetal.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "金属矿石", "颜色值G", Setting::get().ColorMetal.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "金属矿石", "颜色值B", Setting::get().ColorMetal.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "大麻", "颜色值R", Setting::get().ColorHemp.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "大麻", "颜色值G", Setting::get().ColorHemp.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "大麻", "颜色值B", Setting::get().ColorHemp.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "蘑菇", "颜色值R", Setting::get().ColorMushroom.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "蘑菇", "颜色值G", Setting::get().ColorMushroom.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "蘑菇", "颜色值B", Setting::get().ColorMushroom.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "食品盒", "颜色值R", Setting::get().ColorFoodBox.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "食品盒", "颜色值G", Setting::get().ColorFoodBox.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "食品盒", "颜色值B", Setting::get().ColorFoodBox.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "南瓜", "颜色值R", Setting::get().ColorPumpkin.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "南瓜", "颜色值G", Setting::get().ColorPumpkin.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "南瓜", "颜色值B", Setting::get().ColorPumpkin.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玉米", "颜色值R", Setting::get().ColorCorn.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玉米", "颜色值G", Setting::get().ColorCorn.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玉米", "颜色值B", Setting::get().ColorCorn.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "土豆", "颜色值R", Setting::get().Colorpotato.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "土豆", "颜色值G", Setting::get().Colorpotato.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "土豆", "颜色值B", Setting::get().Colorpotato.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "动物", "颜色值R", Setting::get().ColorAnimal.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "动物", "颜色值G", Setting::get().ColorAnimal.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "动物", "颜色值B", Setting::get().ColorAnimal.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "武装坦克", "颜色值R", Setting::get().ColorTank.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "武装坦克", "颜色值G", Setting::get().ColorTank.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "武装坦克", "颜色值B", Setting::get().ColorTank.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "武装直升机", "颜色值R", Setting::get().ColorArmedHelicopter.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "武装直升机", "颜色值G", Setting::get().ColorArmedHelicopter.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "武装直升机", "颜色值B", Setting::get().ColorArmedHelicopter.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "自动炮塔", "颜色值R", Setting::get().ColorTurret.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "自动炮塔", "颜色值G", Setting::get().ColorTurret.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "自动炮塔", "颜色值B", Setting::get().ColorTurret.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "散弹枪陷阱", "颜色值R", Setting::get().ColorTrap.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "散弹枪陷阱", "颜色值G", Setting::get().ColorTrap.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "散弹枪陷阱", "颜色值B", Setting::get().ColorTrap.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "防空炮塔", "颜色值R", Setting::get().ColorAntiaircraftGun.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "防空炮塔", "颜色值G", Setting::get().ColorAntiaircraftGun.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "防空炮塔", "颜色值B", Setting::get().ColorAntiaircraftGun.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "补给箱", "颜色值R", Setting::get().ColorSupplyBox.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "补给箱", "颜色值G", Setting::get().ColorSupplyBox.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "补给箱", "颜色值B", Setting::get().ColorSupplyBox.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "工具箱", "颜色值R", Setting::get().ColorToolBox.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "工具箱", "颜色值G", Setting::get().ColorToolBox.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "工具箱", "颜色值B", Setting::get().ColorToolBox.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "军工箱", "颜色值R", Setting::get().ColorMilitaryBox.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "军工箱", "颜色值G", Setting::get().ColorMilitaryBox.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "军工箱", "颜色值B", Setting::get().ColorMilitaryBox.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "超级军工箱", "颜色值R", Setting::get().ColorSuperbox.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "超级军工箱", "颜色值G", Setting::get().ColorSuperbox.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "超级军工箱", "颜色值B", Setting::get().ColorSuperbox.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "领地柜", "颜色值R", Setting::get().ColorTerritoryBox.x * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "领地柜", "颜色值G", Setting::get().ColorTerritoryBox.y * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "领地柜", "颜色值B", Setting::get().ColorTerritoryBox.z * 255.f);
	miscs::get().WriteIni_int(ConfigPath, "玩家", "最大距离", Setting::get().DistancePlayer);
	miscs::get().WriteIni_int(ConfigPath, "尸体", "最大距离", Setting::get().DistanceCorpse);
	miscs::get().WriteIni_int(ConfigPath, "NPC", "最大距离", Setting::get().DistanceNPC);
	miscs::get().WriteIni_int(ConfigPath, "石头矿石", "最大距离", Setting::get().DistanceStone);
	miscs::get().WriteIni_int(ConfigPath, "硫磺矿石", "最大距离", Setting::get().DistanceSulfur);
	miscs::get().WriteIni_int(ConfigPath, "金属矿石", "最大距离", Setting::get().DistanceMetal);
	miscs::get().WriteIni_int(ConfigPath, "大麻", "最大距离", Setting::get().DistanceHemp);
	miscs::get().WriteIni_int(ConfigPath, "蘑菇", "最大距离", Setting::get().DistanceMushroom);
	miscs::get().WriteIni_int(ConfigPath, "食品盒", "最大距离", Setting::get().DistanceFoodBox);
	miscs::get().WriteIni_int(ConfigPath, "南瓜", "最大距离", Setting::get().DistancePumpkin);
	miscs::get().WriteIni_int(ConfigPath, "玉米", "最大距离", Setting::get().DistanceCorn);
	miscs::get().WriteIni_int(ConfigPath, "土豆", "最大距离", Setting::get().DistancePotato);
	miscs::get().WriteIni_int(ConfigPath, "小飞机", "最大距离", Setting::get().DistanceVehicle);
	miscs::get().WriteIni_int(ConfigPath, "自动炮塔", "最大距离", Setting::get().DistanceAutoTurret);
	miscs::get().WriteIni_int(ConfigPath, "防空炮塔", "最大距离", Setting::get().DistanceNavalGun);
	miscs::get().WriteIni_int(ConfigPath, "超级军工箱", "最大距离", Setting::get().DistanceNiceBox);
	miscs::get().WriteIni_int(ConfigPath, "补给箱", "最大距离", Setting::get().DistanceSupplyBox);
	miscs::get().WriteIni_int(ConfigPath, "工具箱", "最大距离", Setting::get().DistanceToolBox);
	miscs::get().WriteIni_int(ConfigPath, "军工箱", "最大距离", Setting::get().DistanceMilitaryBox);
	miscs::get().WriteIni_int(ConfigPath, "散弹枪陷阱", "最大距离", Setting::get().DistanceShotgunTrap);
	miscs::get().WriteIni_int(ConfigPath, "领地柜", "最大距离", Setting::get().DistanceTerritoryBox);
	miscs::get().WriteIni_int(ConfigPath, "动物", "最大距离", Setting::get().DistanceAnimal);
}
VOID Setting::ReadDistanceSettings() {
	if (miscs::get().exists((miscs::get().GetProgramPath() + "\\Config.ini").c_str()))
	{
		char* ConfigPath = new char[MAX_PATH];
		strcpy(ConfigPath, (miscs::get().GetProgramPath() + "\\Config.ini").c_str());
		this->DistancePlayer = miscs::get().ReadIni_float(ConfigPath, "玩家", "最大距离");
		this->DistanceCorpse = miscs::get().ReadIni_float(ConfigPath, "尸体", "最大距离");
		this->DistanceNPC = miscs::get().ReadIni_float(ConfigPath, "NPC", "最大距离");
		this->DistanceStone = miscs::get().ReadIni_float(ConfigPath, "石头矿石", "最大距离");
		this->DistanceSulfur = miscs::get().ReadIni_float(ConfigPath, "硫磺矿石", "最大距离");
		this->DistanceMetal = miscs::get().ReadIni_float(ConfigPath, "金属矿石", "最大距离");
		this->DistanceHemp = miscs::get().ReadIni_float(ConfigPath, "大麻", "最大距离");
		this->DistanceMushroom = miscs::get().ReadIni_float(ConfigPath, "蘑菇", "最大距离");
		this->DistanceFoodBox = miscs::get().ReadIni_float(ConfigPath, "食品盒", "最大距离");
		this->DistancePumpkin = miscs::get().ReadIni_float(ConfigPath, "南瓜", "最大距离");
		this->DistanceCorn = miscs::get().ReadIni_float(ConfigPath, "玉米", "最大距离");
		this->DistancePotato = miscs::get().ReadIni_float(ConfigPath, "土豆", "最大距离");
		this->DistanceVehicle = miscs::get().ReadIni_float(ConfigPath, "小飞机", "最大距离");
		this->DistanceAutoTurret = miscs::get().ReadIni_float(ConfigPath, "自动炮塔", "最大距离");
		this->DistanceNavalGun = miscs::get().ReadIni_float(ConfigPath, "防空炮塔", "最大距离");
		this->DistanceNiceBox = miscs::get().ReadIni_float(ConfigPath, "超级军工箱", "最大距离");
		this->DistanceSupplyBox = miscs::get().ReadIni_float(ConfigPath, "补给箱", "最大距离");
		this->DistanceToolBox = miscs::get().ReadIni_float(ConfigPath, "工具箱", "最大距离");
		this->DistanceMilitaryBox = miscs::get().ReadIni_float(ConfigPath, "军工箱", "最大距离");
		this->DistanceShotgunTrap = miscs::get().ReadIni_float(ConfigPath, "散弹枪陷阱", "最大距离");
		this->DistanceTerritoryBox = miscs::get().ReadIni_float(ConfigPath, "领地柜", "最大距离");
		this->DistanceAnimal = miscs::get().ReadIni_float(ConfigPath, "动物", "最大距离");
	}
}